### ISSUE TITLE
请问可以继续资源帮助翻译吗？

### ISSUE THREAD

**Issue by scottpedia** [ocftw/ssd.eff.org#22]
你好

我是在中国大陆出生，所以说会的汉语是简体中文。请问我可以帮助继续翻译吗？我要翻译的话在过程中可能会有简体到繁体的转化问题，还有就是用词习惯的问题，对于这些我可能需要一些纠正。

**Comment by pellaeon** [comment]
您好，

若您想要幫助繼續翻譯這個繁體中文的版本，可以直接提交 PR，貢獻本專案的志工會儘量幫您 review 。本專案一如所有其他開源專案，對於 PR 的 review 時間都不固定，沒有任何保證。本專案目前維護人力不足，任何貢獻可能都需要較久的時間才會被接受。另外，希望您不要直接提交機器翻譯簡體中文到繁體中文的結果，因為機器翻譯並不精準。若使用機器翻譯，建議在提交前經過人工檢核，方能確保品質。

若您希望儘快更新內容資訊，或是想要增加簡體中文的內容，建議您可以以本專案的授權條款，複製內容另起爐灶。
